DROP TABLE IF EXISTS HTTP_TREE_NODE;

CREATE TABLE HTTP_TREE_NODE (
        ID BIGINT NOT NULL,
        NAME VARCHAR(100) NOT NULL,
        PROJECT_CODE VARCHAR(100) NOT NULL,
        NODE_TYPE VARCHAR(10) NOT NULL,
        PARENT_ID BIGINT NOT NULL DEFAULT 0,
        ENV_CODE VARCHAR(100),
        METHOD VARCHAR(32),
        URL VARCHAR(256),
        REST_STR VARCHAR(2048),
        COOKIE_STR VARCHAR(2048),
        HEADER_STR VARCHAR(2048),
        PARAM_STR VARCHAR(2048),
        BODY_TYPE VARCHAR(32),
        BODY_LANGUAGE VARCHAR(64),
        BODY_DATA VARCHAR(2048),
        DELETED BOOLEAN NOT NULL DEFAULT true,
        CREATE_USER_ID BIGINT,
        CREATE_TIME TIMESTAMP,
        MODIFY_USER_ID BIGINT,
        MODIFY_TIME TIMESTAMP,
        PRIMARY KEY (ID)
);

COMMENT ON TABLE HTTP_TREE_NODE IS '接口树节点';

COMMENT ON COLUMN HTTP_TREE_NODE.ID IS '接口树节点ID';

COMMENT ON COLUMN HTTP_TREE_NODE.NAME IS '树名称';

COMMENT ON COLUMN HTTP_TREE_NODE.PROJECT_CODE IS '项目编码';

COMMENT ON COLUMN HTTP_TREE_NODE.NODE_TYPE IS '节点类型';

COMMENT ON COLUMN HTTP_TREE_NODE.PARENT_ID IS '父节点';

COMMENT ON COLUMN HTTP_TREE_NODE.METHOD IS '请求方式';

COMMENT ON COLUMN HTTP_TREE_NODE.URL IS '请求路径';

COMMENT ON COLUMN HTTP_TREE_NODE.REST_STR IS 'rest参数';

COMMENT ON COLUMN HTTP_TREE_NODE.COOKIE_STR IS 'cookie参数';

COMMENT ON COLUMN HTTP_TREE_NODE.HEADER_STR IS 'header参数';

COMMENT ON COLUMN HTTP_TREE_NODE.PARAM_STR IS 'param参数';

COMMENT ON COLUMN HTTP_TREE_NODE.BODY_TYPE IS '请求体类型';

COMMENT ON COLUMN HTTP_TREE_NODE.BODY_LANGUAGE IS '请求体语言';

COMMENT ON COLUMN HTTP_TREE_NODE.BODY_DATA IS '请求体数据';

COMMENT ON COLUMN HTTP_TREE_NODE.DELETED IS '是否删除';

COMMENT ON COLUMN HTTP_TREE_NODE.CREATE_USER_ID IS '创建人';

COMMENT ON COLUMN HTTP_TREE_NODE.CREATE_TIME IS '创建时间';

COMMENT ON COLUMN HTTP_TREE_NODE.MODIFY_USER_ID IS '修改人';

COMMENT ON COLUMN HTTP_TREE_NODE.MODIFY_TIME IS '修改时间';
