# 使用 openjdk 17 作为基础镜像
FROM openjdk:17-alpine
# 修改软件源安装 Nginx
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.tencent.com/g' /etc/apk/repositories \
    && apk add --update --no-cache nginx \
    && rm -f /var/cache/apk/*

COPY frontend /frontend
# 将后台服务的可执行文件复制到容器中
COPY /backend /backend
# 配置 Nginx
COPY nginx.conf /etc/nginx/nginx.conf
# 设置工作目录
WORKDIR /backend
# 暴露后台服务和前端静态文件的端口
EXPOSE 12003 12003
EXPOSE 11018 11018
# 启动后台服务和 Nginx
CMD java -jar TestHub.jar & nginx -g "daemon off;"